//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevASPNET {
	
	
	public partial class FrmApplicationSession {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label lblApplication;
		
		protected System.Web.UI.WebControls.Label lblSession;
		
		protected System.Web.UI.WebControls.Label lblSessionID;
		
		protected System.Web.UI.WebControls.Label lblTimeout;
	}
}
